server {
    listen 8080;
    host 0.0.0.0;
    server_name localhost;
    client_max_body_size 1m;

    location / {
        root ./www;
        index index.html;
        allow_methods GET POST;
        autoindex off;
    }

    location /uploads {
        root ./www;
        allow_methods GET POST DELETE;
        autoindex on;
    }

    location /post_body {
        root ./www;
        allow_methods POST;
        client_max_body_size 100;
    }
}
